version: 2.1
jobs:
  build:
      docker: 
      - image: circleci/python:3.6.4
        
      steps:
      - checkout 
      - run: echo "This is a NGINX webServer" 
      - setup_remote_docker
      - run:
        name: Build Image 
        command: docker build -t nginx-web .
